title: Adassa Enterprise Solutions, Inc
email: mail@adassa.com.jm
description: This is the AES, Inc coporate website.
baseurl: ""
url: "https://adassa.com.jm"

# Company Information
company_name: D P Bennett & Associates
address_line: Kingston, Jamaica
telephone_number: 876-289-1644
fax_number: 
company_email: info@dpbennett.com.jm

# Social Link
facebook_link: https://www.facebook.com/desmond.bennett.7731/
twitter_link: https://www.twitter.com/DesmondPBennett
github_link: https://github.com/DPBandA

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
