## Products.
---
- name: Fluval Bug Bites Tropical Fish Food
  categories: Fish Food
  description: Tropical fish food.
  link: https://amzn.to/3R21VDL
  image: https://m.media-amazon.com/images/I/61C9u3+zljL._AC_SX679_.jpg
- name: Fish Flakes
  categories: Fish Food
  description: Tropical fish food.
  link: https://amzn.to/411Y6D7
  image: https://m.media-amazon.com/images/I/41+rg0KULdL._AC_SL230_.jpg
- name: Micro-Lift Fish Pellets
  categories: Fish Food
  description: Tropical fish food.
  link: https://amzn.to/40Y8lsc
  image: https://m.media-amazon.com/images/I/61ODW9ZAHaL._AC_SX569_.jpg