## Products.
---
- name: Fish Flakes
  categories: Fish Food
  description: Tropical fish food.
  link: https://s.click.aliexpress.com/e/_mrDLKdq
  image: https://ae-pic-a1.aliexpress-media.com/kf/S7bc04af131db4812bdba9c8c5db0785bv.jpg
- name: Fish Pellets
  categories: Fish Food
  description: Tropical fish food.
  link: https://s.click.aliexpress.com/e/_ooCFxlt
  image: https://ae-pic-a1.aliexpress-media.com/kf/S0bb4529f55da454c87ae52be300d6733x.jpg
- name: Gnucash 2.4 Small Business Accounting - Beginner's Guide
  categories: Accounting Book
  description: This book is a comprehensive beginner's guide that teaches you to 
               use GnuCash from scratch with jargon-free step-by-step tutorials 
               packed with tips.There are multiple choice questions to make 
               learning more interesting and additional challenges thrown at 
               the more adventurous user for a deep grasp of the topic.
  link: https://amzn.to/48Qwy6x
  image: https://m.media-amazon.com/images/I/71PUXlqDR2L._SL1360_.jpg